[package]
name = "keycursieve"
version = "0.1.0"
authors = ["talljoe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
